CVMSanpham/Controllers/LaptopstoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVMSanpham.Models;
using PagedList;
using PagedList.Mvc;

namespace CVMSanpham.Controllers
{
    public class LaptopstoreController : Controller
    {
        // GET: Laptopstore
        dbQLstoreDataContext data= new dbQLstoreDataContext();
        private List<SanPham> laylapmoi(int count)
        {
            return data.SanPhams.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var lapmoi = laylapmoi(7);
            return View(lapmoi);
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }

        public ActionResult Hang()
        {
            var hang = from h in data.Hangs select h;
            return PartialView(hang);
        }
        [ChildActionOnly]
        public ActionResult _pSanpham(int? page)

        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var Sanpham = from sp in data.SanPhams select sp;
            return PartialView(Sanpham.ToPagedList(pageNum, pageSize));
        }

        public ActionResult Sptheochdue(int id)
        {
            var Sanpham = from s in data.SanPhams where s.MaCD == id select s;
            return View(Sanpham);
        }

        public ActionResult Sptheohang(int id)
        {
            var Sanpham = from s in data.SanPhams where s.MaHang == id select s;
            return View(Sanpham);
        }

        public ActionResult Slider()
        {
            var Slider = from sl in data.Sliders select sl;
            return PartialView(Slider);
        }

        public ActionResult Details(int id)
        {
            var Sanpham = from s in data.SanPhams
                where s.MaSP == id
                select s;
            return View(Sanpham.Single());
        }

        public ActionResult SpPartial (int id)
        {
            var Sanpham = from s in data.SanPhams
                where s.MaSP == id
                select s;
            return View(Sanpham.Single());

        }

        public ActionResult quangcao(int id)
        {
            var quangcao = from qc in data.QuangCaos
                where qc.MaQC== id
                           select qc;

            return PartialView(quangcao);
        }
        public ActionResult Tintuc()
        {
            var tintuc = from tt in data.TinTucs select tt;
            return View(tintuc);
        }
        public ActionResult CTtintuc(int id)
        {
            var tintuc = from tt in data.TinTucs where tt.MaTin == id select tt; 
            return View(tintuc.Single());
        }
    }
}

CVMSanpham/Views/Laptopstore/Chude.cshtml
@model IEnumerable<CVMSanpham.Models.CHUDE>

    @foreach (var item in Model)
    {
        <li>
            <a href="@Url.Action("Sptheochdue", "Laptopstore", new {id = item.MaCD})">


                @item.TenChuDe
            </a>
        </li>
    }

CVMSanpham/Views/Laptopstore/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutSP.cshtml";
}

<div class="single-product-area mb-80">
    <div class="row">
        <!-- imgs-zoom-area start -->
        <div class="col-md-5 col-sm-5 col-xs-12">
            <div class="imgs-zoom-area">
                <img id="zoom_03" src="~/sanpham/@Model.Anhbia" data-zoom-image="~/sanpham/@Model.Anhbia" alt="">
                <div class="row">
                    <div class="col-xs-12">

                    </div>
                </div>
            </div>
        </div>
        <!-- imgs-zoom-area end -->
        <!-- single-product-info start -->
        <div class="col-md-7 col-sm-7 col-xs-12">
            <div class="single-product-info">
                <h3 class="text-black-1">Tên sản phẩm : @Model.TenSP </h3>
                
                <!--  hr -->
                <hr>
                <!-- single-pro-color-rating -->
                <div class="single-pro-color-rating clearfix">
                    <div class="sin-pro-color f-left">
                        <p class="color-title f-left">Color</p>
                        <div class="widget-color f-left">
                            <ul>
                                <li class="color-1"><a href="#"></a></li>
                                <li class="color-2"><a href="#"></a></li>
                                <li class="color-3"><a href="#"></a></li>
                                <li class="color-4"><a href="#"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="pro-rating sin-pro-rating f-right">
                        <a href="#" tabindex="0"><i class="zmdi zmdi-star"></i></a>
                        <a href="#" tabindex="0"><i class="zmdi zmdi-star"></i></a>
                        <a href="#" tabindex="0"><i class="zmdi zmdi-star"></i></a>
                        <a href="#" tabindex="0"><i class="zmdi zmdi-star-half"></i></a>
                        <a href="#" tabindex="0"><i class="zmdi zmdi-star-outline"></i></a>
                        <span class="text-black-5">( 6969 Rating )</span>
                    </div>
                </div>
                <!-- hr -->
                <hr>
                <!-- plus-minus-pro-action -->
                <div class="plus-minus-pro-action clearfix">

                    <div class="sin-pro-action f-right">
                        <ul class="action-button">
                            <li>
                                <a href="#" title="Wishlist" tabindex="0"><i class="zmdi zmdi-favorite"></i></a>
                            </li>
                            <li>
                                <a href="#" data-toggle="modal" data-target="#productModal" title="Quickview" tabindex="0"><i class="zmdi zmdi-zoom-in"></i></a>
                            </li>
                            <li>
                                <a href="#" title="Compare" tabindex="0"><i class="zmdi zmdi-refresh"></i></a>
                            </li>
                            <li>
                                <a href="#" title="Add to cart" tabindex="0"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- plus-minus-pro-action end -->
                <!-- hr -->
                <hr>
                <!-- single-product-price -->
                <h3 class="pro-price" style="color: red">Giá bán khuyến mãi: @Model.GiaHienTai VNĐ</h3>
                <h4 class="pro-price">Giá bán: @Model.GiaCu VNĐ</h4>
                
                <!--  hr -->
                <hr>
                <div>
                    <a href="@Url.Action("ThemGiohang", "GioHang", new {@iMaSP = @Model.MaSP, @strURL = Request.Url.ToString()})" class="button extra-small button-black" tabindex="-1">
                        <span class="text-uppercase">Thêm vào giỏ</span>
                    </a>
                </div>
            </div>
        </div>
        <!-- single-product-info end -->
    </div>
    <!-- single-product-tab -->
    <div class="row">
        <div class="col-md-12">
            <!-- hr -->
            <hr>
            <div class="single-product-tab">
                <ul class="reviews-tab mb-20">
                    <li class="active"><a href="#description" data-toggle="tab" style="color: red">Thông tin sản phẩm</a></li>
                    <li><a href="#information" data-toggle="tab" style="color: red">Thông số kỹ thuật</a></li>
                    <li><a href="#reviews" data-toggle="tab" style="color:blue ">Phản hồi</a></li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="description">
                        <p>@Html.Raw(Model.MoTaCT)</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="information">
                      @Html.Raw(Model.MoTa)
                    </div>
                    <div role="tabpanel" class="tab-pane" id="reviews">
                        <!-- reviews-tab-desc -->
                        <div class="reviews-tab-desc">
                            <!-- single comments -->
                            <div class="media mt-30">
                                <div class="media-left">
                                    <a href="#"><img class="media-object" src="img/author/1.jpg" alt="#"></a>
                                </div>
                                <div class="media-body">
                                    <div class="clearfix">
                                        <div class="name-commenter pull-left">
                                            <h6 class="media-heading"><a href="#">Gerald Barnes</a></h6>
                                            <p class="mb-10">27 Jun, 2017 at 2:30pm</p>
                                        </div>
                                        <div class="pull-right">
                                            <ul class="reply-delate">
                                                <li><a href="#">Reply</a></li>
                                                <li>/</li>
                                                <li><a href="#">Delate</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer accumsan egestas .</p>
                                </div>
                            </div>
                            <!-- single comments -->
                            <div class="media mt-30">
                                <div class="media-left">
                                    <a href="#"><img class="media-object" src="img/author/2.jpg" alt="#"></a>
                                </div>
                                <div class="media-body">
                                    <div class="clearfix">
                                        <div class="name-commenter pull-left">
                                            <h6 class="media-heading"><a href="#">Gerald Barnes</a></h6>
                                            <p class="mb-10">27 Jun, 2017 at 2:30pm</p>
                                        </div>
                                        <div class="pull-right">
                                            <ul class="reply-delate">
                                                <li><a href="#">Reply</a></li>
                                                <li>/</li>
                                                <li><a href="#">Delate</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer accumsan egestas .</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--  hr -->
            <hr>
        </div>
    </div>
</div>

<div id="quickview-wrapper">
    <!-- Modal -->
    <div class="modal fade" id="productModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="modal-product clearfix">
                        <div class="product-images">
                            <div class="main-image images">
                                <img id="zoom_03" src="~/sanpham/@Model.Anhbia" data-zoom-image="~/sanpham/@Model.Anhbia" alt="">
                            </div>
                        </div><!-- .product-images -->

                        <div class="product-info">
                            <h1>Tên sản phẩm : @Model.TenSP</h1>
                            <div class="price-box-3">
                                <div class="s-price-box">
                                    <span class="new-price">@Model.GiaHienTai VNĐ</span>
                                    <span class="old-price">@Model.GiaCu VNĐ</span>
                                </div>
                            </div>
                           
                            <div class="quick-add-to-cart">
                                <form method="post" class="cart">
                                   
                                    <div>
                                        <a href="@Url.Action("ThemGiohang", "GioHang", new {@iMaSP = @Model.MaSP, @strURL = Request.Url.ToString()})" class="button extra-small button-black" tabindex="-1">
                                            <span  class="text-uppercase">Thêm vào giỏ</span>
                                          
                                        </a>
                                    </div>
                                </form>
                            </div>
                            
                            <div class="social-sharing">
                                <div class="widget widget_socialsharing_widget">
                                    <h3 class="widget-title-modal">Chia sẻ sản phẩm</h3>
                                    <ul class="social-icons clearfix">
                                        <li>
                                            <a class="facebook" href="#" target="_blank" title="Facebook">
                                                <i class="zmdi zmdi-facebook"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="google-plus" href="#" target="_blank" title="Google +">
                                                <i class="zmdi zmdi-google-plus"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="twitter" href="#" target="_blank" title="Twitter">
                                                <i class="zmdi zmdi-twitter"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="pinterest" href="#" target="_blank" title="Pinterest">
                                                <i class="zmdi zmdi-pinterest"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="rss" href="#" target="_blank" title="RSS">
                                                <i class="zmdi zmdi-rss"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .product-info -->
                    </div><!-- .modal-product -->
                </div><!-- .modal-body -->
            </div><!-- .modal-content -->
        </div><!-- .modal-dialog -->
    </div>
    <!-- END Modal -->
</div>

CVMSanpham/Views/Laptopstore/Hang.cshtml
@model IEnumerable<CVMSanpham.Models.Hang>

@foreach (var item in Model)
{
    <li>
        <a href="@Url.Action("Sptheohang", "Laptopstore", new {id = item.MaHang})">
            <img alt="@item.AnhHang" src="~/images/@item.AnhHang" />

            
        </a>
    </li>
}

CVMSanpham/Views/Laptopstore/Index.cshtml
@model IEnumerable<CVMSanpham.Models.SanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@foreach (var sanpham in Model)
{


    <!-- product-item start -->
    <div class="col-xs-12">
        <div class="product-item product-item-2">
            <div class="product-img">
                <a href="@Url.Action("Details", "Laptopstore", new {id = sanpham.MaSP})">
                    <img alt="@sanpham.TenSP" src="~/sanpham/@sanpham.Anhbia" width="220"/>
                </a>
            </div>
            <div class="product-info">
                <h6 class="product-title">
                    <a href="single-product.html">@sanpham.TenSP</a>
                </h6>
                <h3 class="pro-price" style="color: red">@sanpham.GiaHienTai VNĐ</h3>

            </div>
            <ul class="action-button">
                <li>
                    <a href="#" title="Wishlist"><i class="zmdi zmdi-favorite"></i></a>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#productModal" title="Quickview"><i class="zmdi zmdi-zoom-in"></i></a>
                </li>
                <li>
                    <a href="#" title="Compare"><i class="zmdi zmdi-refresh"></i></a>
                </li>
                <li>
                    <a href="#" title="Add to cart"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <!--asd-->
 



}

CVMSanpham/Views/Laptopstore/Slider.cshtml
@model IEnumerable<CVMSanpham.Models.Slider>
<div class="slider-area  plr-185  mb-80">
<div class="container-fluid">
<div class="slider-content">
    <div class="row">
        <div class="active-slider-1 slick-arrow-1 slick-dots-1">
        @foreach (var Slider in Model)
        {
            <!-- START SLIDER AREA -->

            
            <!-- layer-1 Start -->
            <div class="col-md-12">
                <div class="layer-1">
                    <div class="slider-img">
                        <img src="~/images/@Slider.UrlHinh" width=200 />
                    </div>
                    <div class="slider-info gray-bg">
                        <div class="slider-info-inner">
                            <h1 style="color: #1792ec">@Slider.Title</h1>
                            <h3 style="color: #00c2ff">@Slider.Tenhinh</h3>
                            <div class="slider-brief text-black-2">
                                <p>@Slider.review</p>
                            </div>
                            <a href="@Slider.LinkUrl" class="button extra-small button-black">
                                <span class="text-uppercase">Xem chi tiết</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- layer-1 end -->
          

        }
    </div>
            </div>
        </div>
    </div>
        <!-- END SLIDER AREA -->
    </div>


<!-- END SLIDER AREA -->>

CVMSanpham/Views/Laptopstore/SpPartial.cshtml
     
                
                    <div class="modal-product clearfix">
                        <div class="product-images">
                            <div class="main-image images">
                                <img alt="" src="img/product/quickview.jpg">
                            </div>
                        </div><!-- .product-images -->

                        <div class="product-info">
                            <h1>Aenean eu tristique</h1>
                            <div class="price-box-3">
                                <div class="s-price-box">
                                    <span class="new-price">£160.00</span>
                                    <span class="old-price">£190.00</span>
                                </div>
                            </div>
                            <a href="single-product-left-sidebar.html" class="see-all">See all features</a>
                            <div class="quick-add-to-cart">
                                <form method="post" class="cart">
                                    <div class="numbers-row">
                                        <input type="number" id="french-hens" value="3">
                                    </div>
                                    <button class="single_add_to_cart_button" type="submit">Add to cart</button>
                                </form>
                            </div>
                            <div class="quick-desc">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor. Donec non est at libero.
                            </div>
                            <div class="social-sharing">
                                <div class="widget widget_socialsharing_widget">
                                    <h3 class="widget-title-modal">Share this product</h3>
                                    <ul class="social-icons clearfix">
                                        <li>
                                            <a class="facebook" href="#" target="_blank" title="Facebook">
                                                <i class="zmdi zmdi-facebook"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="google-plus" href="#" target="_blank" title="Google +">
                                                <i class="zmdi zmdi-google-plus"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="twitter" href="#" target="_blank" title="Twitter">
                                                <i class="zmdi zmdi-twitter"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="pinterest" href="#" target="_blank" title="Pinterest">
                                                <i class="zmdi zmdi-pinterest"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="rss" href="#" target="_blank" title="RSS">
                                                <i class="zmdi zmdi-rss"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .product-info -->
                    </div><!-- .modal-product -->
         
  

CVMSanpham/Views/Laptopstore/Sptheochdue.cshtml
@{
    ViewBag.Title = "Sptheochdue";
    Layout = "~/Views/Shared/_LayoutCDH.cshtml";
}

@foreach (var sanpham in Model)
{
    <!-- product-item start -->
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="product-item">
            <div class="product-img">
                <a href="@Url.Action("Details", "Laptopstore", new {id = sanpham.MaSP})">
                    <img alt="@sanpham.TenSP" src="~/sanpham/@sanpham.Anhbia" width="220" />
                </a>
            </div>
            <div class="product-info">
                <h6 class="product-title">
                    <a href="single-product.html">@sanpham.TenSP</a>
                </h6>
                <div class="pro-rating">
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star-half"></i></a>
                    <a href="#"><i class="zmdi zmdi-star-outline"></i></a>
                </div>
                <h3 class="pro-price">@sanpham.GiaHienTai VNĐ</h3>
                <ul class="action-button">
                    <li>
                        <a href="#" title="Wishlist"><i class="zmdi zmdi-favorite"></i></a>
                    </li>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#productModal" title="Quickview"><i class="zmdi zmdi-zoom-in"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Compare"><i class="zmdi zmdi-refresh"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Add to cart"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- product-item end -->
}

CVMSanpham/Views/Laptopstore/Sptheohang.cshtml
@{
    ViewBag.Title = "Sptheohang";
    Layout = "~/Views/Shared/_LayoutCDH.cshtml";
}

@foreach (var sanpham in Model)
{
      <!-- product-item start -->
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="product-item">
            <div class="product-img">
                <a href="@Url.Action("Details", "Laptopstore", new {id = sanpham.MaSP})">
                    <img alt="@sanpham.TenSP" src="~/sanpham/@sanpham.Anhbia" width="220" />
                </a>
            </div>
            <div class="product-info">
                <h6 class="product-title">
                    <a href="single-product.html">@sanpham.TenSP</a>
                </h6>
                <div class="pro-rating">
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star-half"></i></a>
                    <a href="#"><i class="zmdi zmdi-star-outline"></i></a>
                </div>
                <h3 class="pro-price">@sanpham.GiaHienTai VNĐ</h3>
                <ul class="action-button">
                    <li>
                        <a href="#" title="Wishlist"><i class="zmdi zmdi-favorite"></i></a>
                    </li>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#productModal" title="Quickview"><i class="zmdi zmdi-zoom-in"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Compare"><i class="zmdi zmdi-refresh"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Add to cart"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
                                        <!-- product-item end -->
}

CVMSanpham/Views/Laptopstore/_pSanpham.cshtml
@using CVMSanpham.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
@foreach (var sanpham in Model)
{
    <div class="col-md-3 col-sm-4 col-xs-12">
        <div class="product-item">
            <div class="product-img">
                <a href="@Url.Action("Details", "Laptopstore", new {id = sanpham.MaSP})">
                    <img alt="@sanpham.TenSP" src="~/sanpham/@sanpham.Anhbia" width="220" />
                </a>
            </div>
            <div class="product-info">
                <h6 class="product-title">
                    <a href="single-product.html">@sanpham.TenSP</a>
                </h6>
                <div class="pro-rating">
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star"></i></a>
                    <a href="#"><i class="zmdi zmdi-star-half"></i></a>
                    <a href="#"><i class="zmdi zmdi-star-outline"></i></a>
                </div>
                <h3 class="pro-price">@sanpham.GiaHienTai VNĐ</h3>
                <ul class="action-button">
                    <li>
                        <a href="#" title="Wishlist"><i class="zmdi zmdi-favorite"></i></a>
                    </li>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#productModal" title="Quickview"><i class="zmdi zmdi-zoom-in"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Compare"><i class="zmdi zmdi-refresh"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Add to cart"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
}
@*tao lien ket*@
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))

</div>
<style>
        .MenuTrang li {
            display: inline;
        }
    </style>

CVMSanpham/Views/Laptopstore/quangcao.cshtml
@using CVMSanpham.Models
@model IEnumerable<CVMSanpham.Models.QuangCao>
@foreach (var quangcao in Model)
{
    <div class="col-md-4 hidden-sm col-xs-12">
        <div class="banner-item banner-1">
            <div class="ribbon-price">
                <span></span>
            </div>
            <div class="banner-img">
                <a href="@quangcao.LinkUrl">
                    <img src="~/images/@quangcao.AnhQC" width="300" />
                                    
                </a>
            </div>
            <div class="banner-info">
                <h3><a href="@quangcao.LinkUrl"></a></h3>                            
            </div>
        </div>
    </div>
}